name: Generate Hugo static files and deploy to Amazon S3

on:
  push:
    branches:
      - main  # Adjust branch name as necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.138.0'
          extended: true

      - name: Build
        run: hugo --baseURL http://essays.kjonasj.com -D

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: us-east-2

      - name: List generated files
        run: ls -R ./public

      - name: Sync files to S3 subfolder
        run: |
          aws s3 sync ./public s3://essays.kjonasj.com --delete
